#!/bin/bash

FILE_NAME=$PYFILE

# remove the file extension
MAIN_NAME="${PYFILE%.py}"
#construct the output file by removing .py and appending .pyc
OUTPUTNAME="${PYFILE%.py}.pyc"

# compile
python3 -m py_compile "$PYFILE"
# rename
mv "__pycache__/${MAIN_NAME}."* "${OUTPUTNAME}"

# delete the pycache folder
rm -r __pycache__
